/* min/MIDI.js/examples/inc/colorspace.js */

/* min/MIDI.js/js/midi/audioDetect-1909386c.js */
/* min/MIDI.js/js/midi/loadPlugin-1909386c.js */
/* min/MIDI.js/js/midi/player-1909386c.js */
/* min/MIDI.js/js/midi/plugin-1909386c.js */

/* min/MusicTheory.js */

(function(b){b.btoa||(b.btoa=function(a){a=escape(a);var b="",e,d,k="",m,g,f="",l=0;do e=a.charCodeAt(l++),d=a.charCodeAt(l++),k=a.charCodeAt(l++),m=e>>2,e=(e&3)<<4|d>>4,g=(d&15)<<2|k>>6,f=k&63,isNaN(d)?g=f=64:isNaN(k)&&(f=64),b=b+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(m)+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(e)+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(g)+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(f);
while(l<a.length);return b});b.atob||(b.atob=function(a){var b="",e,d,k="",m,g="",f=0;/[^A-Za-z0-9\+\/\=]/g.exec(a)&&alert("There were invalid base64 characters in the input text.\nValid base64 characters are A-Z, a-z, 0-9, '+', '/',and '='\nExpect errors in decoding.");a=a.replace(/[^A-Za-z0-9\+\/\=]/g,"");do e="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(a.charAt(f++)),d="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(a.charAt(f++)),m="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(a.charAt(f++)),
g="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(a.charAt(f++)),e=e<<2|d>>4,d=(d&15)<<4|m>>2,k=(m&3)<<6|g,b+=String.fromCharCode(e),64!=m&&(b+=String.fromCharCode(d)),64!=g&&(b+=String.fromCharCode(k));while(f<a.length);return unescape(b)})})(this);


if("undefined"===typeof DOM)var DOM={};
(function(){DOM.dimensions=function(){document.body&&(document.body.scrollHeight||(document.body.scrollHeight=Math.max(document.body.scrollHeight,document.documentElement.scrollHeight)),window.innerWidth&&window.innerHeight||(document.body&&document.body.offsetWidth?(window.innerWidth=document.body.offsetWidth,window.innerHeight=document.body.offsetHeight):"CSS1Compat"===document.compatMode&&(document.documentElement&&document.documentElement.offsetWidth)&&(window.innerWidth=document.documentElement.offsetWidth,
window.innerHeight=document.documentElement.offsetHeight)))}})();


/* min/json2.js */


window.requestAnimationFrame||(window.requestAnimationFrame=function(){return window.webkitRequestAnimationFrame||window.mozRequestAnimationFrame||window.oRequestAnimationFrame||window.msRequestAnimationFrame||function(b,a){window.setTimeout(b,1E3/60)}}());

String.prototype.replaceAll=function(b,a){if("object"==typeof b){for(var c=this,e=0;e<b.length;e++)c=c.split(b[e]).join(a[e]);return c}return this.split(b).join(a)};
String.prototype.trim=function(b){return this.replace(/^\s+|\s+$/g,"")};
String.prototype.ucfirst=function(b){return this[0].toUpperCase()+this.substr(1)};
String.prototype.ucwords=function(b){return this.replace(/^(.)|\s(.)/g,function(a){return a.toUpperCase()})};
String.prototype.addslashes=function(){return this.replace(/([\\"'])/g,"\\$1").replace(/\0/g,"\\0")};
String.prototype.stripslashes=function(){return this.replace(/\0/g,"0").replace(/\\([\\'"])/g,"$1")};
String.format=function(b){var a=Array.prototype.slice.call(arguments,1,arguments.length);return b.replace(/\{(\d+)\}/g,function(b,e){return a[e]})};
String.prototype.basename=function(){return this.replace(/\\/g,"/").replace(/.*\//,"")};


if("undefined"===typeof widgets)var widgets={};
(function(){var b={"text/css":"string","text/html":"string","text/plain":"string"};widgets.FileSaver=function(a){"undefined"===typeof a&&(a={});var c=a.jsDir||"./inc/",e=this;this.html5="function"===typeof ArrayBuffer;this.boot=function(){var b=window.BlobBuilder||window.WebKitBlobBuilder||window.MozBlobBuilder,d=window.btoa&&window.atob,g=[];g.push({src:c+"File/jszip.js",verify:"JSZip"});d||g.push({src:c+"Polyfill/Base64.js",verify:["atob","btoa"]});b||g.push({src:c+"Polyfill/BlobBuilder.js",verify:"BlobBuilder"});
e.html5?g.push({src:c+"File/FileSaver.js",verify:"saveAs"}):g.push({src:c+"File/downloadify.js",verify:["Downloadify","swfobject"]});DOMLoader.script.add({srcs:g,callback:function(){if(a.onready)a.onready(e)}});return this};this.download=function(a){if("function"===typeof saveAs&&"function"===typeof BlobBuilder&&a.getData){var c=a.getData(),e=a.name,f=a.mime,l=a.charset;a=a.extension;var n="";if("string"===typeof c){if("data:"===c.substr(0,5)){var r=c.substr(5).split(","),c=r[1],f=r[0].split(";")[0];
a||(a=f.split("/")[1]);b[r[0]]||(n="binary")}}else n="binary",f="application/zip",a="zip",c=d(c);e||(e="download");f||(f="text/plain");a||(a="txt");n||(n=b[f]||"binary");r=new BlobBuilder;if("string"===n)r.append(c),l&&(f+=";charset="+l);else{for(var c=atob(c),l=new ArrayBuffer(c.length),n=new Uint8Array(l),q=0;q<c.length;q++)n[q]=c.charCodeAt(q);r.append(l)}f=r.getBlob(f);saveAs(f,e+"."+a)}};this.button=function(a){var b=a.parent||document.body,g=a.id,f=a.fileName,l=a.fileType,n=a.getData,r="fake"===
a.format,q=document.createElement("span"),p=document.createElement("span");p.id=g;p.style.position="absolute";q.style.cssText="width: inherit; height: inherit;";q.className="downloadify-container";q.appendChild(p);var s=document.createElement("span");s.style.cssText="width: inherit; height: inherit;";s.className="downloadify";a.src?(p=new Image,p.src=a.src,s.appendChild(p)):s.innerHTML=a.title?a.title:f+"."+l;q.appendChild(s);b.appendChild(q);setTimeout(function(){var p=b.offsetWidth,v=b.offsetHeight;
q.style.width=p+"px";q.style.height=v+"px";var w=document.getElementById(g);e.html5||r?Event.add(s,"click",function(){if(r)return n();e.download({name:f,extension:l,getData:n})}):(Event.add(w,"mousedown",Event.stop),Downloadify.create(g,{filename:function(){return f+"."+l},data:function(){var a=n();return"string"===typeof a?a:d(a)},downloadImage:c+"File/downloadify.png",swf:c+"File/downloadify.swf",transparent:!0,append:!1,width:p,height:v,dataType:a.format}))},1)};var d=function(a){function c(a,
d){var e=a.data,f={};-1!==e.indexOf("base64")&&(e=e.split(";"),b[e[0].substr(5)]&&(f.binary=!1),f.base64=!0,e=e[1].substr(7));d.add(a.name,e,f)}var d=new JSZip;if("undefined"===typeof a.length)if(a.data&&a.name)a=[a];else{for(var e in a)for(var l=a[e],n=d.folder(e),r=0,q=l.length;r<q;r++)c(l[r],n);return d.generate()}r=0;for(q=a.length;r<q;r++)c(a[r],d);return d.generate()};return this.boot()}})();


"undefined"===typeof widgets&&(widgets={});
(function(){var b=Math.PI,a=!document.createElement("canvas").getContext,c={id:"loader",bars:12,radius:0,lineWidth:20,lineHeight:70,timeout:0,display:!0};widgets.Loader=function(k){if(!a){var m=this;"string"===typeof k&&(k={message:k});"boolean"===typeof k&&(k={display:!1});"undefined"===typeof k&&(k={});k.container=k.container||document.body;if(k.container){for(var g in c)"undefined"===typeof k[g]&&(k[g]=c[g]);var f=document.getElementById(k.id);if(f)this.span=f.parentNode.getElementsByTagName("span")[0];
else{var l=document.createElement("div");g=document.createElement("span");g.className="message";l.appendChild(g);l.className=c.id;l.style.cssText=e("opacity",400);this.span=g;this.div=l;f=document.createElement("canvas");document.body.appendChild(f);f.id=k.id;f.style.cssText="opacity: 1; position: absolute; z-index: 10000;";l.appendChild(f);k.container.appendChild(l)}var n=k.bars,r=k.radius,q=2*(k.lineHeight+20)+2*k.radius;d(k.container);var p=window.devicePixelRatio||1;f.width=q*p;f.height=q*p;var s=
0,t=f.getContext("2d");t.globalCompositeOperation="lighter";t.shadowOffsetX=1;t.shadowOffsetY=1;t.shadowBlur=1;t.shadowColor="rgba(0, 0, 0, 0.5)";this.messages={};this.message=function(a,b){return this.interval?this.add({message:a,onstart:b}):this.start(b,a)};this.update=function(a,b,c){if(!a)for(a in this.messages);if(!a)return this.message(b);a=this.messages[a];a.message=b;"number"===typeof c&&(a.span.innerHTML=c+"%");"..."===b.substr(-3)?(a._message=b.substr(0,b.length-3),a.messageAnimate=[".&nbsp;&nbsp;",
"..&nbsp;","..."].reverse()):(a._message=b,a.messageAnimate=!1);a.element.innerHTML=b};this.add=function(a){"string"===typeof a&&(a={message:a});this.span.style.cssText="background: "+(k.background?k.background:"rgba(0,0,0,0.65)")+";";this.div.style.cssText=e("opacity",400);this.div.style.cssText=this.stopPropagation?this.div.style.cssText+"background: rgba(0,0,0,0.25);":this.div.style.cssText+"pointer-events: none;";f.parentNode.style.opacity=1;f.parentNode.style.display="block";k.background&&(this.div.style.background=
k.backgrond);var b=(new Date).getTime(),c=Math.abs(b*Math.random()>>0),d=a.message,g=document.createElement("div");g.style.cssText=e("opacity",500);var l=document.createElement("span");l.style.cssText="float: right; width: 50px;";var n=document.createElement("span");n.innerHTML=d;g.appendChild(n);g.appendChild(l);b=this.messages[c]={seed:c,container:g,element:n,span:l,message:d,timeout:1E3*(a.timeout||k.timeout),timestamp:b,getProgress:a.getProgress};this.span.appendChild(g);this.span.style.display=
"block";this.update(b.seed,d);a.onstart&&window.setTimeout(a.onstart,50);this.center();this.interval||(a.delay||w(),window.clearInterval(this.interval),this.interval=window.setInterval(w,30));return c};this.remove=function(a){s+=0.07;(new Date).getTime();"object"===typeof a&&(a=a.join(":"));a&&(a=":"+a+":");for(var b in this.messages){var c=this.messages[b];a&&-1===a.indexOf(":"+c.seed+":")||(delete this.messages[c.seed],c.container.style.color="#99ff88",v(c),c.getProgress&&(c.span.innerHTML="100%"))}};
this.start=function(a,b){if(b||k.message)return this.add({message:b||k.message,onstart:a})};this.stop=function(){this.remove();window.clearInterval(this.interval);delete this.interval;if(k.oncomplete)k.oncomplete();f&&f.style&&(l.style.cssText+="pointer-events: none;",window.setTimeout(function(){m.div.style.opacity=0},1),window.setTimeout(function(){m.interval||(m.stopPropagation=!1,f.parentNode.style.display="none",t.clearRect(0,0,q,q))},4E5))};this.center=function(){var a=d(k.container),b=a.height-
q;f.style.left=(a.width-q)/2+"px";f.style.top=b/2+"px";f.style.width=q+"px";f.style.height=q+"px";m.span.style.top=b/2+q-10+"px"};g=document.createElement("style");g.innerHTML=".loader { color: #fff; position: fixed; left: 0; top: 0; width: 100%; height: 100%; z-index: 100000; opacity: 0; display: none; }.loader span.message { font-family: monospace; font-size: 14px; margin: auto; opacity: 1; display: none; border-radius: 10px; padding: 0px; width: 300px; text-align: center; position: absolute; z-index: 10000; left: 0; right: 0; }.loader span.message div { border-bottom: 1px solid #222; padding: 5px 10px; clear: both; text-align: left; opacity: 1; }.loader span.message div:last-child { border-bottom: none; }";
document.head.appendChild(g);var v=function(a){window.setTimeout(function(){a.container.style.opacity=0},1);window.setTimeout(function(){a.container.parentNode.removeChild(a.container)},250)},w=function(){var a=(new Date).getTime(),c;for(c in m.messages){var d=m.messages[c],e=s/0.07>>0;if(0===e%5&&d.getProgress){if(d.timeout&&d.timestamp&&a-d.timestamp>d.timeout){m.remove(d.seed);continue}var f=d.getProgress();if(100<=f){m.remove(d.seed);continue}d.span.innerHTML=(f>>0)+"%"}0===e%10&&d.messageAnimate&&
(d.element.innerHTML=d._message+d.messageAnimate[e/10%d.messageAnimate.length])}c||m.stop();t.save();t.clearRect(0,0,q*p,q*p);t.scale(p,p);t.translate(q/2,q/2);a=360-360/n;for(c=0;c<n;c++){d=2*(c/n)*b+s;t.save();t.translate(r*Math.sin(-d),r*Math.cos(-d));t.rotate(d);var d=-k.lineWidth/2,e=k.lineWidth,f=k.lineHeight,g=e/2;t.beginPath();t.moveTo(d+g,0);t.lineTo(d+e-g,0);t.quadraticCurveTo(d+e,0,d+e,0+g);t.lineTo(d+e,0+f-g);t.quadraticCurveTo(d+e,0+f,d+e-g,0+f);t.lineTo(d+g,0+f);t.quadraticCurveTo(d,
0+f,d,0+f-g);t.lineTo(d,0+g);t.quadraticCurveTo(d,0,d+g,0);t.fillStyle="hsla("+c/(n-1)*a+", 100%, 50%, 0.85)";t.fill();t.restore()}t.restore();s+=0.07};if(!1===k.display)return this;this.start();return this}}};var e=function(a,b){return"\t\t-webkit-transition-property: "+a+";\t\t-webkit-transition-duration: "+b+"ms;\t\t-moz-transition-property: "+a+";\t\t-moz-transition-duration: "+b+"ms;\t\t-o-transition-property: "+a+";\t\t-o-transition-duration: "+b+"ms;\t\t-ms-transition-property: "+a+";\t\t-ms-transition-duration: "+
b+"ms;"},d=function(a){if(window.innerWidth&&window.innerHeight)var b=window.innerWidth,d=window.innerHeight;else"CSS1Compat"===document.compatMode&&document.documentElement&&document.documentElement.offsetWidth?(b=document.documentElement.offsetWidth,d=document.documentElement.offsetHeight):document.body&&document.body.offsetWidth&&(b=document.body.offsetWidth,d=document.body.offsetHeight);a&&(b=a.offsetWidth);return{width:b,height:d}}})();


"undefined"===typeof widgets&&(widgets={});
widgets.Uploader=function(b){b||(b={});var a=this;this.uploadPath="./gallery-upload.php";this.callback=b.callback;this.maxFiles=((this.singleFile=b.singleFile||!1)?1:b.max)||Infinity;this.fileCollection={};this.hasFileReader=window.FileReader?!0:!1;this.acceptedFormats=b.formats||{"image/jpg":!0,"image/jpeg":!0,"image/gif":!0,"image/png":!0};this.uploadCollection=function(b){var d=[],c=this.fileCollection,e;for(e in c)d.push(c[e]);a.handleFiles(d,{upload:!0,callback:b})};this.preview=function(b){var d=
b.name,e=function(b){a.fileCollection[d].src=b.target.result;a.fileCollection[d].preview=!0;return c()},f=new FileReader;f.addEventListener?f.addEventListener("loadend",e,!1):f.onloadend=e;f.readAsDataURL(b)};this.upload=function(b){var d=b.name;if(a.hasFileReader){var e=function(b){switch(b.target.error.code){case b.target.error.NOT_FOUND_ERR:a.status="File not found.";break;case b.target.error.NOT_READABLE_ERR:a.status="File not readable.";break;case b.target.error.ABORT_ERR:a.status="Upload has been aborted.";
break;default:a.status="Read error."}},f=function(b){b.lengthComputable&&(a.status=Math.round(100*b.loaded/b.total))},l=function(e){var f=new XMLHttpRequest;f.onreadystatechange=function(b){if(4===f.readyState&&"success"===b.srcElement.responseText)return a.fileCollection[d].uploaded=!0,c()};"undefined"!==typeof f.sendAsBinary?(f.open("POST",a.uploadPath+"?upload=true",!0),e="--xxxxxxxxx\r\n"+("Content-Disposition: form-data; name='upload'; filename='"+b.name+"'\r\n"),e=e+"Content-Type: application/octet-stream\r\n\r\n"+
(n.result+"\r\n"),e+="--xxxxxxxxx\r\n",f.setRequestHeader("content-type","multipart/form-data; boundary=xxxxxxxxx"),f.sendAsBinary(e)):(f.open("POST",a.uploadPath+"?upload=true&base64=true",!0),f.setRequestHeader("X-FILENAME",b.name),f.setRequestHeader("X-FILESIZE",b.size),f.setRequestHeader("X-FILETYPE",b.type),f.send(window.btoa(n.result)))},n=new FileReader;"undefined"!==typeof n.addEventListener?(n.addEventListener("loadend",l,!1),n.addEventListener("error",e,!1),n.addEventListener("progress",
f,!1)):(n.onloadend=l,n.onerror=e,n.onprogress=f);n.readAsBinaryString(b)}else{var r=new XMLHttpRequest;r.onreadystatechange=function(b){if(4===r.readyState&&"success"===b.srcElement.responseText)return a.fileCollection[d].uploaded=!0,c()};r.open("POST",a.uploadPath+"?upload=true",!0);r.setRequestHeader("X-FILENAME",b.name);r.setRequestHeader("X-FILESIZE",b.size);r.setRequestHeader("X-FILETYPE",b.type);r.send(b)}};var c;this.handleFiles=function(b,d){var e=0,f=b.length;d||(d={});0<f&&(a.singleFile&&
!0!==d.upload)&&(a.fileCollection={});(c=function(){var l=b[e],n={status:a.status,current:e,length:f};if(++e>a.maxFiles||!l)a.callback(n,a.fileCollection,f-1,d.event);else{a.callback(n);n=l.name;if(a.fileCollection[n])if(d.upload){if(a.fileCollection[n].uploaded)return c()}else if(a.fileCollection[n].preview)return c();a.fileCollection[n]=l;(n=l.type)||(n="text/"+l.fileName.substr(l.fileName.lastIndexOf(".")+1));if(!a.acceptedFormats[n])return console.log(n+"is not an accepted format."),c();if(0===
(l.fileSize||l.size))return console.log("file is empty."),c();if(d.upload)a.upload(l);else if(d.preview&&a.hasFileReader)a.preview(l);else return c()}})()};var e=document.createElement("form");e.action="#";e.method="post";e.enctype="multipart/form-data";e.style.cssText="z-index: 10000; position: absolute; left: 0; top: 0; display: none;";e.addEventListener("dragenter",function(a){Event.prevent(a);Event.stop(a);e.style.background="rgba(255,0,0,0.2)";return!1},!1);e.addEventListener("dragover",function(a){Event.prevent(a);
Event.stop(a);return!1},!1);e.addEventListener("drop",function(b){Event.prevent(b);Event.stop(b);e.style.display="none";e.style.background="none";b.dataTransfer&&b.dataTransfer.files&&a.handleFiles(b.dataTransfer.files,{preview:!0,event:b})},!1);e.addEventListener("dragleave",function(a){Event.prevent(a);Event.stop(a);window.setTimeout(function(){e.style.display="none";e.style.background="none"},100)},!1);var d=document.createElement("input");d.type="file";d.name="files[]";!this.singleFile&&1<this.maxFiles&&
(d.multiple="multiple");d.style.cssText="position: absolute; opacity: 0;";d.addEventListener("change",function(b){d.files&&d.files[0]?a.handleFiles(d.files,{preview:!0,event:b}):d.value&&console.log(d.value)},!1);d.addEventListener("click",function(a){Event.prevent(a);Event.stop(a)},!1);e.appendChild(d);b=function(a){!window.innerWidth&&(document.body&&document.body.offsetWidth)&&(window.innerWidth=document.body.offsetWidth,window.innerHeight=document.body.offsetHeight);window.innerWidth&&window.innerHeight&&
(e.style.width=window.innerWidth+"px",e.style.height=window.innerHeight+"px")};b();window.addEventListener("dragenter",function(a){e.style.display="block"},!1);window.addEventListener("resize",b,!1);document.body.appendChild(e);return this};


/* min/DOMLoader.js */

/* min/XMLHttpRequest.js */

/* min/MIDI.js/examples/inc/event.js */

/* min/MIDI.js/inc/jasmid/stream.js */

/* min/MIDI.js/inc/jasmid/midifile.js */

/* min/MIDI.js/inc/jasmid/replayer.js */


(function(b){function a(a){return String.fromCharCode.apply(null,a)}function c(a,b){if(b)for(;a.length/2<b;)a="0"+a;for(var d=[],c=a.length-1;0<=c;c-=2)d.unshift(parseInt(0===c?a[c]:a[c-1]+a[c],16));return d}var e=Array.prototype;if(!b.console||!console.firebug){var d=["log","debug","info","warn","error"];b.console={};for(var k=0;k<d.length;++k)b.console[d[k]]=function(){}}var m={G9:127,Gb9:126,F9:125,E9:124,Eb9:123,D9:122,Db9:121,C9:120,B8:119,Bb8:118,A8:117,Ab8:116,G8:115,Gb8:114,F8:113,E8:112,
Eb8:111,D8:110,Db8:109,C8:108,B7:107,Bb7:106,A7:105,Ab7:104,G7:103,Gb7:102,F7:101,E7:100,Eb7:99,D7:98,Db7:97,C7:96,B6:95,Bb6:94,A6:93,Ab6:92,G6:91,Gb6:90,F6:89,E6:88,Eb6:87,D6:86,Db6:85,C6:84,B5:83,Bb5:82,A5:81,Ab5:80,G5:79,Gb5:78,F5:77,E5:76,Eb5:75,D5:74,Db5:73,C5:72,B4:71,Bb4:70,A4:69,Ab4:68,G4:67,Gb4:66,F4:65,E4:64,Eb4:63,D4:62,Db4:61,C4:60,B3:59,Bb3:58,A3:57,Ab3:56,G3:55,Gb3:54,F3:53,E3:52,Eb3:51,D3:50,Db3:49,C3:48,B2:47,Bb2:46,A2:45,Ab2:44,G2:43,Gb2:42,F2:41,E2:40,Eb2:39,D2:38,Db2:37,C2:36,B1:35,
Bb1:34,A1:33,Ab1:32,G1:31,Gb1:30,F1:29,E1:28,Eb1:27,D1:26,Db1:25,C1:24,B0:23,Bb0:22,A0:21,Ab0:20,G0:19,Gb0:18,F0:17,E0:16,Eb0:15,D0:14,Db0:13,C0:12},g=function(a){if(!a||null===a.type&&void 0===a.type||null===a.channel&&void 0===a.channel||null===a.param1&&void 0===a.param1)throw Error("Not enough parameters to create an event.");this.setTime(a.time);this.setType(a.type);this.setChannel(a.channel);this.setParam1(a.param1);this.setParam2(a.param2)};g.createNote=function(a,b){if(!a)throw Error("Note not specified");
if("string"===typeof a)a=m[a];else if(!a.pitch)throw Error("The pitch is required in order to create a note.");var d=[];d.push(g.noteOn(a));b||d.push(g.noteOff(a,a.duration||128));return d};g.noteOn=function(a,b){return new g({time:a.duration||b||0,type:9,channel:a.channel||0,param1:a.pitch||a,param2:a.volume||90})};g.noteOff=function(a,b){return new g({time:a.duration||b||0,type:8,channel:a.channel||0,param1:a.pitch||a,param2:a.volume||90})};g.prototype={type:0,channel:0,time:0,setTime:function(a){var b=
a||0;for(a=b&127;b>>=7;)a<<=8,a|=b&127|128;for(b=[];;)if(b.push(a&255),a&128)a>>=8;else break;this.time=b},setType:function(a){if(8>a||14<a)throw Error("Trying to set an unknown event: "+a);this.type=a},setChannel:function(a){if(0>a||15<a)throw Error("Channel is out of bounds.");this.channel=a},setParam1:function(a){this.param1=a},setParam2:function(a){this.param2=a},toBytes:function(){var a=[],b=parseInt(this.type.toString(16)+this.channel.toString(16),16);a.push.apply(a,this.time);a.push(b);a.push(this.param1);
void 0!==this.param2&&null!==this.param2&&a.push(this.param2);return a}};var f=function(a){a&&(this.setType(a.type),this.setData(a.data))};f.prototype={setType:function(a){this.type=a},setData:function(a){this.data=a},toBytes:function(){if(!this.type||!this.data)throw Error("Type or data for meta-event not specified.");var a=[255,this.type];this.data&&(this.data.concat&&this.data.unshift&&!this.data.callee)&&e.push.apply(a,this.data);return a}};var l=function(a){this.events=[];for(var b in a)if(a.hasOwnProperty(b))this["set"+
b.charAt(0).toUpperCase()+b.substring(1)](a[b])};l.TRACK_START=[77,84,114,107];l.TRACK_END=[0,255,47,0];l.prototype={addEvent:function(a){this.events.push(a);return this},setEvents:function(a){e.push.apply(this.events,a);return this},setText:function(a,b){b||(b=a=1);return this.addEvent(new f({type:a,data:b}))},setCopyright:function(a){return this.setText(2,a)},setTrackName:function(a){return this.setText(3,a)},setInstrument:function(a){return this.setText(4,a)},setLyric:function(a){return this.setText(5,
a)},setMarker:function(a){return this.setText(6,a)},setCuePoint:function(a){return this.setText(7,a)},setTempo:function(a){this.addEvent(new f({type:81,data:a}))},setTimeSig:function(){},setKeySig:function(){},toBytes:function(){var a=0,b=[],d=l.TRACK_START,f=l.TRACK_END;this.events.forEach(function(d){d=d.toBytes();a+=d.length;e.push.apply(b,d)});var a=a+f.length,g=c(a.toString(16),4);return d.concat(g,b,f)}};b.MidiWriter=function(d){if(d){d=d.tracks||[];var e=d.length.toString(16),f="MThd\x00\x00\x00\u0006\x00\x00",
f=f+a(c(e,2)),f=f+"\u0001\u0090";d.forEach(function(b){f+=a(b.toBytes())});return{b64:btoa(f),play:function(){if(document){var a=document.createElement("embed");a.setAttribute("src","data:audio/midi;base64,"+this.b64);a.setAttribute("type","audio/midi");document.body.appendChild(a)}},save:function(){b.open("data:audio/midi;base64,"+this.b64,"JSMidi generated output","resizable=yes,scrollbars=no,status=no")}}}throw Error("No parameters have been passed to MidiWriter.");};b.MidiEvent=g;b.MetaEvent=
f;b.MidiTrack=l;b.noteTable=m})(jsmidi={});


(function(b){b.btoa||(b.btoa=function(a){a=escape(a);var b="",e,d,k="",m,g,f="",l=0;do e=a.charCodeAt(l++),d=a.charCodeAt(l++),k=a.charCodeAt(l++),m=e>>2,e=(e&3)<<4|d>>4,g=(d&15)<<2|k>>6,f=k&63,isNaN(d)?g=f=64:isNaN(k)&&(f=64),b=b+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(m)+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(e)+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(g)+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(f);
while(l<a.length);return b});b.atob||(b.atob=function(a){var b="",e,d,k="",m,g="",f=0;/[^A-Za-z0-9\+\/\=]/g.exec(a)&&alert("There were invalid base64 characters in the input text.\nValid base64 characters are A-Z, a-z, 0-9, '+', '/',and '='\nExpect errors in decoding.");a=a.replace(/[^A-Za-z0-9\+\/\=]/g,"");do e="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(a.charAt(f++)),d="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(a.charAt(f++)),m="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(a.charAt(f++)),
g="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(a.charAt(f++)),e=e<<2|d>>4,d=(d&15)<<4|m>>2,k=(m&3)<<6|g,b+=String.fromCharCode(e),64!=m&&(b+=String.fromCharCode(d)),64!=g&&(b+=String.fromCharCode(k));while(f<a.length);return unescape(b)})})(this);


String.prototype.replaceAll=function(b,a){if("object"===typeof b){for(var c=this,e=0;e<b.length;e++)c=c.split(b[e]).join(a[e]);return c}return this.split(b).join(a)};
String.prototype.trim=function(b){return this.replace(/^\s+|\s+$/g,"")};
String.prototype.ucfirst=function(b){return this[0].toUpperCase()+this.substr(1)};
String.prototype.ucwords=function(b){return this.replace(/^(.)|\s(.)/g,function(a){return a.toUpperCase()})};
String.prototype.addslashes=function(){return this.replace(/([\\"'])/g,"\\$1").replace(/\0/g,"\\0")};
String.prototype.stripslashes=function(){return this.replace(/\0/g,"0").replace(/\\([\\'"])/g,"$1")};
String.prototype.basename=function(){return this.replace(/\\/g,"/").replace(/.*\//,"")};
String.prototype.lpad=function(b,a){for(var c=this;c.length<a;)c=b+c;return c};
String.prototype.rpad=function(b,a){for(var c=this;c.length<a;)c+=b;return c};

window.STRING=String;
STRING.prototype.replaceAll=STRING.prototype.replaceAll;
STRING.prototype.trim=STRING.prototype.trim;
STRING.prototype.ucfirst=STRING.prototype.ucfirst;
STRING.prototype.ucwords=STRING.prototype.ucwords;
STRING.prototype.addslashes=STRING.prototype.addslashes;
STRING.prototype.stripslashes=STRING.prototype.stripslashes;
STRING.prototype.basename=STRING.prototype.basename;
STRING.prototype.lpad=STRING.prototype.lpad;
STRING.prototype.rpad=STRING.prototype.rpad;


window.localStorage||(window.localStorage={getItem:function(b){return b&&this.hasOwnProperty(b)?unescape(document.cookie.replace(RegExp("(?:^|.*;\\s*)"+escape(b).replace(/[\-\.\+\*]/g,"\\$&")+"\\s*\\=\\s*((?:[^;](?!;))*[^;]?).*"),"$1")):null},key:function(b){return unescape(document.cookie.replace(/\s*\=(?:.(?!;))*$/,"").split(/\s*\=(?:[^;](?!;))*[^;]?;\s*/)[b])},setItem:function(b,a){b&&(document.cookie=escape(b)+"="+escape(a)+"; path=/",this.length=document.cookie.match(/\=/g).length)},length:document.cookie.match(/\=/g).length,
removeItem:function(b){if(b&&this.hasOwnProperty(b)){var a=new Date;a.setDate(a.getDate()-1);document.cookie=escape(b)+"=; expires="+a.toGMTString()+"; path=/";this.length--}},hasOwnProperty:function(b){return RegExp("(?:^|;\\s*)"+escape(b).replace(/[\-\.\+\*]/g,"\\$&")+"\\s*\\=").test(document.cookie)}});


var Base64Binary={_keyStr:"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=",decodeArrayBuffer:function(b){var a=Math.ceil(3*b.length/4),a=new ArrayBuffer(a);this.decode(b,a);return a},decode:function(b,a){var c=this._keyStr.indexOf(b.charAt(b.length-1)),e=this._keyStr.indexOf(b.charAt(b.length-1)),d=Math.ceil(3*b.length/4);64==c&&d--;64==e&&d--;var k,m,g,f,l=0,n=0,c=a?new Uint8Array(a):new Uint8Array(d);b=b.replace(/[^A-Za-z0-9\+\/\=]/g,"");for(l=0;l<d;l+=3)k=this._keyStr.indexOf(b.charAt(n++)),
m=this._keyStr.indexOf(b.charAt(n++)),e=this._keyStr.indexOf(b.charAt(n++)),f=this._keyStr.indexOf(b.charAt(n++)),k=k<<2|m>>4,m=(m&15)<<4|e>>2,g=(e&3)<<6|f,c[l]=k,64!=e&&(c[l+1]=m),64!=f&&(c[l+2]=g);return c}};


"use strict";
var self=this;
self.URL=self.URL||self.webkitURL;
self.requestFileSystem=self.requestFileSystem||self.webkitRequestFileSystem;
self.resolveLocalFileSystemURL=self.resolveLocalFileSystemURL||self.webkitResolveLocalFileSystemURL;

navigator.temporaryStorage=navigator.temporaryStorage||navigator.webkitTemporaryStorage;
navigator.persistentStorage=navigator.persistentStorage||navigator.webkitPersistentStorage;
self.BlobBuilder=self.BlobBuilder||self.MozBlobBuilder||self.WebKitBlobBuilder;

if(void 0===self.FileError){var FileError=function(){};FileError.prototype.prototype=Error.prototype}

var Util={toArray:function(b){return Array.prototype.slice.call(b||[],0)},strToDataURL:function(b,a,c){return(void 0!=c?c:1)?"data:"+a+";base64,"+self.btoa(b):"data:"+a+","+b},strToObjectURL:function(b,a){for(var c=new Uint8Array(b.length),e=0;e<c.length;++e)c[e]=b.charCodeAt(e);c=new Blob([c],a?{type:a}:{});return self.URL.createObjectURL(c)},fileToObjectURL:function(b){return self.URL.createObjectURL(b)},fileToArrayBuffer:function(b,a,c){var e=new FileReader;e.onload=function(b){a(b.target.result)};
e.onerror=function(a){c&&c(a)};e.readAsArrayBuffer(b)},dataURLToBlob:function(b){if(-1==b.indexOf(";base64,")){var a=b.split(",");b=a[0].split(":")[1];a=decodeURIComponent(a[1]);return new Blob([a],{type:b})}a=b.split(";base64,");b=a[0].split(":")[1];for(var a=window.atob(a[1]),c=a.length,e=new Uint8Array(c),d=0;d<c;++d)e[d]=a.charCodeAt(d);return new Blob([e],{type:b})},arrayBufferToBlob:function(b,a){var c=new Uint8Array(b);return new Blob([c],a?{type:a}:{})},arrayBufferToBinaryString:function(b,
a,c){var e=new FileReader;e.onload=function(b){a(b.target.result)};e.onerror=function(a){c&&c(a)};b=new Uint8Array(b);e.readAsBinaryString(new Blob([b]))},arrayToBinaryString:function(b){if("object"!=typeof b)return null;for(var a=b.length,c=Array(a);a--;)c[a]=String.fromCharCode(b[a]);return c.join("")},getFileExtension:function(b){var a=b.lastIndexOf(".");return-1!=a?b.substring(a):""}},
MyFileError=function(b){this.prototype=FileError.prototype;this.code=b.code;this.name=b.name};


FileError.BROWSER_NOT_SUPPORTED=1E3;
FileError.prototype.__defineGetter__("name",function(){for(var b=Object.keys(FileError),a=0,c;c=b[a];++a)if(FileError[c]==this.code)return c;return"Unknown Error"});

var Filer=new function(){function b(b){if(a=b||null)c=a.root,e=!0}var a=null,c=null,e=!1,d=function(b){0!=b.indexOf("filesystem:")&&(b="/"==b[0]?a.root.toURL()+b.substring(1):0==b.indexOf("./")||0==b.indexOf("../")?"../"==b&&c!=a.root?c.toURL()+"/"+b:c.toURL()+b:c.toURL()+"/"+b);return b},k=function(a,b){var c=arguments[1],e=arguments[2],k=function(a){if(a.code==FileError.NOT_FOUND_ERR){if(e)throw Error('"'+c+'" or "'+e+'" does not exist.');throw Error('"'+c+'" does not exist.');}throw Error("Problem getting Entry for one or more paths.");
},m=d(c);if(3==arguments.length){var p=d(e);self.resolveLocalFileSystemURL(m,function(b){self.resolveLocalFileSystemURL(p,function(d){a(b,d)},k)},k)}else self.resolveLocalFileSystemURL(m,a,k)},m=function(b,d,c,e,m,q){if(!a)throw Error("Filesystem has not been initialized.");if(typeof b!=typeof d)throw Error("These method arguments are not supported.");var p=c||null,s=void 0!=q?q:!1;(b.isFile||d.isDirectory)&&d.isDirectory?s?b.moveTo(d,p,e,m):b.copyTo(d,p,e,m):k(function(a,b){if(b.isDirectory)s?a.moveTo(b,
p,e,m):a.copyTo(b,p,e,m);else{var d=Error('Oops! "'+b.name+" is not a directory!");if(m)m(d);else throw d;}},b,d)};b.DEFAULT_FS_SIZE=1048576;b.version="0.4.3";b.prototype={get fs(){return a},get isOpen(){return e},get cwd(){return c}};b.prototype.pathToFilesystemURL=function(a){return d(a)};b.prototype.init=function(b,d,k){if(!self.requestFileSystem)throw new MyFileError({code:FileError.BROWSER_NOT_SUPPORTED,name:"BROWSER_NOT_SUPPORTED"});b=b?b:{};var m=b.size||1048576;this.type=self.TEMPORARY;"persistent"in
b&&b.persistent&&(this.type=self.PERSISTENT);var r=function(b){this.size=m;a=b;c=a.root;e=!0;d&&d(b)};this.type==self.PERSISTENT&&navigator.persistentStorage?navigator.persistentStorage.requestQuota(m,function(a){self.requestFileSystem(this.type,a,r.bind(this),k)}.bind(this),k):self.requestFileSystem(this.type,m,r.bind(this),k)};b.prototype.ls=function(b,d,e){if(!a)throw Error("Filesystem has not been initialized.");var m=function(a){c=a;var b=[],g=c.createReader(),k=function(){g.readEntries(function(a){a.length?
(b=b.concat(Util.toArray(a)),k()):(b.sort(function(a,b){return a.name<b.name?-1:b.name<a.name?1:0}),d(b))},e)};k()};b.isDirectory?m(b):0==b.indexOf("filesystem:")?k(m,b):c.getDirectory(b,{},m,e)};b.prototype.mkdir=function(b,d,e,k){if(!a)throw Error("Filesystem has not been initialized.");var m=null!=d?d:!1,q=b.split("/"),p=function(a,d){if("."==d[0]||""==d[0])d=d.slice(1);a.getDirectory(d[0],{create:!0,exclusive:m},function(a){if(a.isDirectory)d.length&&1!=q.length?p(a,d.slice(1)):e&&e(a);else if(a=
Error(b+" is not a directory"),k)k(a);else throw a;},function(a){if(a.code==FileError.INVALID_MODIFICATION_ERR)if(a.message="'"+b+"' already exists",k)k(a);else throw a;})};p(c,q)};b.prototype.open=function(b,c,e){if(!a)throw Error("Filesystem has not been initialized.");b.isFile?b.file(c,e):k(function(a){a.file(c,e)},d(b))};b.prototype.create=function(b,d,e,k){if(!a)throw Error("Filesystem has not been initialized.");c.getFile(b,{create:!0,exclusive:null!=d?d:!0},e,function(a){a.code==FileError.INVALID_MODIFICATION_ERR&&
(a.message="'"+b+"' already exists");if(k)k(a);else throw a;})};b.prototype.mv=function(a,b,d,c,e){m.bind(this,a,b,d,c,e,!0)()};b.prototype.rm=function(b,d,c){if(!a)throw Error("Filesystem has not been initialized.");var e=function(a){a.isFile?a.remove(d,c):a.isDirectory&&a.removeRecursively(d,c)};b.isFile||b.isDirectory?e(b):k(e,b)};b.prototype.cd=function(b,e,l){if(!a)throw Error("Filesystem has not been initialized.");b.isDirectory?(c=b,e&&e(c)):(b=d(b),k(function(a){if(a.isDirectory)c=a,e&&e(c);
else if(a=Error("Path was not a directory."),l)l(a);else throw a;},b))};b.prototype.cp=function(a,b,d,c,e){m.bind(this,a,b,d,c,e)()};b.prototype.write=function(b,d,e,m){if(!a)throw Error("Filesystem has not been initialized.");var r=function(a){a.createWriter(function(b){b.onerror=m;if(d.append)b.onwriteend=function(b){e&&e(a,this)},b.seek(b.length);else{var c=!1;b.onwriteend=function(b){c?e&&e(a,this):(c=!0,this.truncate(this.position))}}d.data.__proto__==ArrayBuffer.prototype&&(d.data=new Uint8Array(d.data));
var k=new Blob([d.data],d.type?{type:d.type}:{});b.write(k)},m)};b.isFile?r(b):0==b.indexOf("filesystem:")?k(r,b):c.getFile(b,{create:!0,exclusive:!1},r,m)};b.prototype.df=function(a,b){var d=function(b,d){a(b,d-b,d)};if(!navigator.temporaryStorage.queryUsageAndQuota||!navigator.persistentStorage.queryUsageAndQuota)throw Error("Not implemented.");self.TEMPORARY==this.type?navigator.temporaryStorage.queryUsageAndQuota(d,b):self.PERSISTENT==this.type&&navigator.persistentStorage.queryUsageAndQuota(d,
b)};return b};


/* min/Piano/piano_canvas.js */

/* min/Piano/piano_animation.js */

/* min/Piano/piano_notes_playing.js */

/* min/Piano/piano_render.js */


var MusicBox={};
(function(){function b(b){a.aspect=window.innerWidth/window.innerHeight;a.updateProjectionMatrix();e.setSize(window.innerWidth,window.innerHeight)}var a,c,e,d,k=[],m="#interactive"==window.location.hash,g;MusicBox.init=function(){d=document.createElement("div");d.id="musicbox";d.style.cssText="position: absolute; top: 0; left: 0; z-index: 0";d.onmousemove=MusicBox.render;document.body.appendChild(d);a=new THREE.TrackballCamera({fov:200,aspect:window.innerWidth/window.innerHeight,near:0,far:1E3,rotateSpeed:1,
zoomSpeed:1.2,panSpeed:0.8,noZoom:!1,noPan:!1,staticMoving:!1,dynamicDampingFactor:0.3});a.position.x=900;a.position.y=-100;a.position.z=-100;MusicBox.scene=new THREE.Scene;MusicBox.scene.fog=new THREE.FogExp2(0,0.0025);var f=new THREE.DirectionalLight(13421772,4);f.position.x=1;f.position.y=1;f.position.z=1;f.position.normalize();MusicBox.scene.addLight(f);f=new THREE.DirectionalLight(16777215,4);f.position.x=-1;f.position.y=-1;f.position.z=-1;f.position.normalize();MusicBox.scene.addLight(f);for(var f=
0,k=new THREE.CubeGeometry(100,40,40),g=1;9>g;g++)for(var m=0;12>m;m++){var q=new THREE.Mesh(k,new THREE.MeshLambertMaterial({color:parseInt("0x"+Piano.colorMap[f++].hex),transparent:!0,blending:THREE.AdditiveBlending}));q.position.x=1E3*(m/36)-50;q.position.y=1E3*(g/10)-500;q.position.z=1E3*(m/10)-400;q.sticky=!0;MusicBox.scene.addObject(q)}k=new THREE.Geometry;for(i=0;4E3>i;i++)vector=new THREE.Vector3(2E3*Math.random()-1E3,2E3*Math.random()-1E3,2E3*Math.random()-1E3),k.vertices.push(new THREE.Vertex(vector));
parameters=[[[1,1,1],5],[[0.95,1,1],4],[[0.9,1,1],3],[[0.85,1,1],2],[[0.8,1,1],1]];c=new THREE.Projector;e=new THREE.WebGLRenderer;e.sortObjects=!1;e.setSize(window.innerWidth,window.innerHeight);d.appendChild(e.domElement);window.addEventListener("resize",b,!1)};MusicBox.render=function(){a.update();if(m){var b=new THREE.Vector3(0,0,0.5);c.unprojectVector(b,a);b=(new THREE.Ray(a.position,b.subSelf(a.position).normalize())).intersectScene(MusicBox.scene);0<b.length?g!=b[0].object&&(g&&(g.scale.x=
1),g=b[0].object,g.currentHex=g.materials[0].color.hex,MIDI.noteOn&&(b=Color.Space(g.currentHex,"HEX>RGB>HSL"),b=(12*(b.H/360)>>0)+12*(b.L/10>>0),g.scale.x=100,MIDI.noteOn(1,b))):(g&&(g.scale.x=1),g=null)}b=1E-4*(new Date).getTime();for(i=0;i<MusicBox.scene.objects.length;i++){var d=MusicBox.scene.objects[i];d.sticky||(d.rotation.y=b*(4>i?i/70:-i/70))}for(i=0;i<k.length;i++)color=parameters[i][0],h=360*(color[0]+b)%360/360,k[i].color.setHSV(h,color[1],color[2]);e.render(MusicBox.scene,a)}})();


var change=function(){return{css:function(b,a){"string"===typeof b&&(b=document.getElementById(b));if(b){a=a.split(";");for(var c=0,e=a.length;c<e;c++){var d=a[c].split(":");b.style[d[0]]=d[1]}}},className:function(b,a){"string"===typeof b&&(b=document.getElementById(b));if(b){if(b.parentNode){var c=b.parentNode.getElementsByClassName(a);if(c.length)for(var e=0;e<c.length;e++)c[e].className=(" "+c[e].className+" ").replace(" "+a+" "," ").trim()}b.className=(b.className+" "+a).trim()}}}}();


"undefined"===typeof MIDI&&(MIDI={});
"undefined"===typeof MIDI.UI&&(MIDI.UI={});
(function(b){b.enableConfigure=function(a){var b=document.getElementById("tools").parentNode.style;a?(Event.remove(window,"keydown",Piano.keyDown),Event.remove(window,"keyup",Piano.keyUp),b.display="block"):(Event.add(window,"keydown",Piano.keyDown),Event.add(window,"keyup",Piano.keyUp),b.display="none")};b.enableView=function(a){"postview"===Piano.visualize?(MIDI.UI.enableTheoryView(),a||Piano.func()):MIDI.UI.enableSongView()};b.enableTheoryView=function(){Piano.setAnimation();change.className("view-theory",
"selected");document.querySelector("#view-song").className="selected theorymode";var a=document.getElementById("playback");"none"!==a.style.display&&(a.style.display="none",a=document.getElementById("theory"),a.style.display="inline-block",a.loaded||(a.loaded=!0,b.drawKeySignatures(a),b.drawOctaves(a),b.drawChords(a),b.drawInversions(a),b.drawScales(a)),Piano.visualize="postview",localStorage.setItem("visualize",Piano.visualize),Piano.Animation.boot())};b.enableSongView=function(){Piano.clearNotes();
change.className("view-song","selected");document.querySelector("#view-song").className="selected songmode";var a=document.getElementById("playback");"inline-block"!==a.style.display&&(a.style.display="inline-block",document.getElementById("theory").style.display="none",Piano.visualize="preview",localStorage.setItem("visualize",Piano.visualize),Piano.Animation.boot())};b.drawKeySignatures=function(a){var b=MIDI.noteToKey[Piano.key+21].replace(/[^a-zA-Z]+/g,"");a.appendChild(e({arr:MusicTheory.key2number,
header:{Signature:null},id:"key",title:"Key Signature",callback:function(a){a=a.options[a.selectedIndex].value;Piano.key=MusicTheory.key2number[a];Piano.inversion=0;MusicTheory.getKeySignature(a);Piano.drawKeyboard();Piano.func()},selected:b}))};b.drawOctaves=function(a){for(var b={},c=0;7>c;c++)b[c+" "]=c;a.appendChild(e({arr:b,header:{Octave:null},id:"octave",callback:function(a){Piano.octave=parseInt(a.options[a.selectedIndex].value);Piano.inversion=0;Piano.clearNotes();Piano.func()},selected:Piano.octave,
title:"Octaves"}))};b.drawChords=function(a){a.appendChild(e({arr:MusicTheory.Chords,id:"chord",header:{Chords:null},callback:function(a){Piano.chord=a.options[a.selectedIndex].value;Piano.func=function(){Piano.clearNotes();Piano.chordOn()};Piano.func();Piano.inversion=0},selected:Piano.chord,title:"Chords"}))};b.drawScales=function(a){var b=0,c=[],g;for(g in MusicTheory.Scales)c[b++]=g;Piano.scale=c[Math.round(Math.random()*b)];a.appendChild(e({arr:MusicTheory.Scales,id:"scale",header:{Scales:null},
callback:function(a){Piano.scale=a.options[a.selectedIndex].value;Piano.func=Piano.playScale;Piano.clearNotes();Piano.func();Piano.inversion=0},selected:Piano.scale,title:"Scales"}))};b.drawInversions=function(a){var b=document.createElement("input");b.type="button";b.title="Inversion -1";b.value="-";b.onclick=function(){Piano.clearNotes();Piano.invert(-1)};a.appendChild(b);b=document.createElement("input");b.type="button";b.title="Inversion +1";b.value="+";b.onclick=function(){Piano.clearNotes();
Piano.invert(1)};a.appendChild(b)};b.togglePlayer=function(a){var b=document.getElementById("control-play"),c="boolean"!==typeof a;c||b.setAttribute("toggled",a);a=b.getAttribute("toggled");"true"===a?(b.setAttribute("toggled",!1),b.src="./media/pause.png",Piano.clearNotes(),c&&(Piano.resume(),Piano.setAnimation())):(b.setAttribute("toggled",!0),b.src="./media/play.png",c&&MIDI.Player.pause())};b.drawTimeWarp=function(){var b=document.createElement("div");b.style.cssText="display: inline-block;";
var c,e,g=document.createElement("input");g.style.cssText="display: inline-block; width: 190px; position: relative; top: 4px;";g.setAttribute("type","range");g.max=400;g.min=100;g.value=100*Piano.timeWarp;g.onmousedown=function(a){e=MIDI.Player.currentTime;c=MIDI.Player.endTime;Event.stop(a);MIDI.Player.playing&&MIDI.UI.togglePlayer()};g.onchange=function(a){var b=g.value/100;a=(b<Piano.timeWarp?"Increasing":"Decreasing")+" speed...";Piano.timeWarp=b;localStorage.setItem("timeWarp",b);loader.message(a);
window.setTimeout(function(){MIDI.Player.timeWarp=b;MIDI.Player.loadMidiFile();MIDI.Player.currentTime=Piano.Animation.scrollTop=e/c*MIDI.Player.endTime;MIDI.Player.renderScreen();loader.stop()},10);f.innerHTML=Math.round(1E4*(1.25-g.value/400))/100+"%"};b.appendChild(g);var f=document.createElement("span");f.style.cssText="display: inline-block; color: #333; width: 30px; padding-left: 10px";f.innerHTML=g.value+"%";b.appendChild(f);a("Playback Speed:",b)};b.drawSynesthesia=function(){var b=e({arr:MusicTheory.Synesthesia.data,
id:"rgb",callback:function(a){Piano.HSL=a.options[a.selectedIndex].value;localStorage.setItem("HSL",Piano.HSL);Piano.colorMap=MusicTheory.Synesthesia.map(Piano.HSL);Piano.drawKeyboard();MIDI.Player.renderScreen();MIDI.Player.playing||(Piano.clearNotes(),Piano.func(),Piano.inversion=0)},selected:Piano.HSL,title:"Synesthesia"});a("Synesthesia:",b,!0)};b.drawInstruments=function(){String(MIDI.getInstruments()).split("|").splice(0,128);var c={},k="",m;for(m in MIDI.instruments){var g=MIDI.instruments[m];
g.instrument&&(k!=g.category&&(k=g.category,c[k]=null),c[g.instrument]=m)}a("Instrument",e({arr:c,id:"voice",title:"Instruments",callback:function(a){Piano.clearNotes();b.instrument=a.options[a.selectedIndex].value;MIDI.Plugin&&MIDI.programChange(b.channel,c[b.instrument]);MIDI.Player.playing||Piano.func()},selected:b.instrument}))};b.drawChannels=function(){for(var d={},k=0;16>k;k++)d[k+" "]=k;k=document.createElement("div");k.style.cssText="display: inline-block;";k.appendChild(e({arr:d,header:{Channels:null},
id:"channel",callback:function(a){b.channel=parseInt(a.options[a.selectedIndex].value);a=MIDI.channels[b.channel];document.getElementById("mute").checked=a.mute?"checked":"";document.getElementById("voice").selectedIndex=a.instrument},selected:0,title:"Channels"}));k.appendChild(c({title:"Mute channel",id:"mute",checked:!1,value:"Mute channel",callback:function(){Piano.clearNotes();MIDI.channels[b.channel].mute=this.checked;MIDI.setMute(b.channel,this.checked)}}));a("Channels",k)};var a=function(a,
b,c){var e=document.getElementById("tools"),f=document.createElement("span");f.innerHTML=a;!1!==c&&e.appendChild(document.createElement("hr"));e.appendChild(f);e.appendChild(b)},c=function(a){a||(a={});var b=document.createElement("input");b.title=a.title;b.id=a.id;b.type="checkbox";b.value=a.value;b.checked=a.checked?a.checked:"";b.onmousedown=function(a){Event.stop(a)};b.onclick=a.callback;return b},e=function(a){var b=document.createElement("select");b.id=a.id;b.title=a.title;b.onmousedown=function(a){Event.stop(a)};
b.onchange=function(b){a.callback(this,b);this.blur()};if(a.header){var c=a.header,e;for(e in a.arr)c[e]=a.arr[e];a.arr=c}for(e in a.arr)null===a.arr[e]?(c=document.createElement("optgroup"),c.label="-"+e.toUpperCase()+"-"):(c=document.createElement("option"),a.selected==e&&(c.selected=!0),c.value=e,c.text=e),b.appendChild(c);return b}})(MIDI.UI);
